/*
 * generated by Xtext
 */
package edu.upb.compilacion.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.upb.compilacion.services.ListaCompilerGrammarAccess;

public class ListaCompilerParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ListaCompilerGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected edu.upb.compilacion.parser.antlr.internal.InternalListaCompilerParser createParser(XtextTokenStream stream) {
		return new edu.upb.compilacion.parser.antlr.internal.InternalListaCompilerParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Lista";
	}
	
	public ListaCompilerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ListaCompilerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
