/*
 * generated by Xtext
 */
package edu.upb.compilacion.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractListaCompilerValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(edu.upb.compilacion.listaCompiler.ListaCompilerPackage.eINSTANCE);
		return result;
	}
}
