/*
 * generated by Xtext
 */
package edu.upb.compilacion;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ListaCompilerStandaloneSetup extends ListaCompilerStandaloneSetupGenerated{

	public static void doSetup() {
		new ListaCompilerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

