grammar edu.upb.compilacion.ListaCompiler with org.eclipse.xtext.common.Terminals

generate listaCompiler "http://www.upb.edu/compilacion/ListaCompiler"

Lista:
	"Holi" name=STRING;

Function: name=IDFUNCVAR "(" (param+=IDFUNCVAR (',' param+=IDFUNCVAR)* '->')? ")";

IntList: 
	"["(INTEGER + ("," INTEGER)*)?"]"
;

terminal INTEGER: '-'?INT;

terminal BOOL: "true" | "false";

terminal IDFUNCVAR: ('a'..'z')('A'..'Z'|'a'..'z')*;