/*
 * generated by Xtext
 */
package edu.upb.compilacion.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import edu.upb.compilacion.services.ListaCompilerGrammarAccess;

public class ListaCompilerParser extends AbstractContentAssistParser {
	
	@Inject
	private ListaCompilerGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser createParser() {
		edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser result = new edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getListaAccess().getLinesAlternatives_0(), "rule__Lista__LinesAlternatives_0");
					put(grammarAccess.getTermAccess().getAlternatives(), "rule__Term__Alternatives");
					put(grammarAccess.getMyIntegerAccess().getAlternatives(), "rule__MyInteger__Alternatives");
					put(grammarAccess.getMyBoolAccess().getAlternatives(), "rule__MyBool__Alternatives");
					put(grammarAccess.getFunctionCallAccess().getAlternatives(), "rule__FunctionCall__Alternatives");
					put(grammarAccess.getListElemAccess().getAlternatives(), "rule__ListElem__Alternatives");
					put(grammarAccess.getBoolAccess().getAlternatives(), "rule__Bool__Alternatives");
					put(grammarAccess.getPDFunctionAccess().getAlternatives(), "rule__PDFunction__Alternatives");
					put(grammarAccess.getFirstLevelOpAccess().getAlternatives(), "rule__FirstLevelOp__Alternatives");
					put(grammarAccess.getSecondLevelOpAccess().getAlternatives(), "rule__SecondLevelOp__Alternatives");
					put(grammarAccess.getThirdLevelOpAccess().getAlternatives(), "rule__ThirdLevelOp__Alternatives");
					put(grammarAccess.getFourthLevelOpAccess().getAlternatives(), "rule__FourthLevelOp__Alternatives");
					put(grammarAccess.getEvaluationAccess().getGroup(), "rule__Evaluation__Group__0");
					put(grammarAccess.getFunctionDefinitionAccess().getGroup(), "rule__FunctionDefinition__Group__0");
					put(grammarAccess.getFunctionDefinitionAccess().getGroup_2(), "rule__FunctionDefinition__Group_2__0");
					put(grammarAccess.getFunctionDefinitionAccess().getGroup_2_1(), "rule__FunctionDefinition__Group_2_1__0");
					put(grammarAccess.getFirstLevelExpAccess().getGroup(), "rule__FirstLevelExp__Group__0");
					put(grammarAccess.getFirstLevelExpAccess().getGroup_1(), "rule__FirstLevelExp__Group_1__0");
					put(grammarAccess.getSecondLevelExpAccess().getGroup(), "rule__SecondLevelExp__Group__0");
					put(grammarAccess.getSecondLevelExpAccess().getGroup_1(), "rule__SecondLevelExp__Group_1__0");
					put(grammarAccess.getThirdLevelExpAccess().getGroup(), "rule__ThirdLevelExp__Group__0");
					put(grammarAccess.getThirdLevelExpAccess().getGroup_1(), "rule__ThirdLevelExp__Group_1__0");
					put(grammarAccess.getFourthLevelExpAccess().getGroup(), "rule__FourthLevelExp__Group__0");
					put(grammarAccess.getFourthLevelExpAccess().getGroup_1(), "rule__FourthLevelExp__Group_1__0");
					put(grammarAccess.getNegIntegerAccess().getGroup(), "rule__NegInteger__Group__0");
					put(grammarAccess.getNegBoolAccess().getGroup(), "rule__NegBool__Group__0");
					put(grammarAccess.getIfControlFlowAccess().getGroup(), "rule__IfControlFlow__Group__0");
					put(grammarAccess.getPreDefFunctionCallAccess().getGroup(), "rule__PreDefFunctionCall__Group__0");
					put(grammarAccess.getPreDefFunctionCallAccess().getGroup_2(), "rule__PreDefFunctionCall__Group_2__0");
					put(grammarAccess.getPreDefFunctionCallAccess().getGroup_2_1(), "rule__PreDefFunctionCall__Group_2_1__0");
					put(grammarAccess.getUserDefFunctionCallAccess().getGroup(), "rule__UserDefFunctionCall__Group__0");
					put(grammarAccess.getUserDefFunctionCallAccess().getGroup_2(), "rule__UserDefFunctionCall__Group_2__0");
					put(grammarAccess.getUserDefFunctionCallAccess().getGroup_2_1(), "rule__UserDefFunctionCall__Group_2_1__0");
					put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
					put(grammarAccess.getListAccess().getGroup_2(), "rule__List__Group_2__0");
					put(grammarAccess.getListAccess().getGroup_2_1(), "rule__List__Group_2_1__0");
					put(grammarAccess.getListaAccess().getLinesAssignment(), "rule__Lista__LinesAssignment");
					put(grammarAccess.getEvaluationAccess().getReturnAssignment_1(), "rule__Evaluation__ReturnAssignment_1");
					put(grammarAccess.getFunctionDefinitionAccess().getNameAssignment_0(), "rule__FunctionDefinition__NameAssignment_0");
					put(grammarAccess.getFunctionDefinitionAccess().getParamsAssignment_2_0(), "rule__FunctionDefinition__ParamsAssignment_2_0");
					put(grammarAccess.getFunctionDefinitionAccess().getParamsAssignment_2_1_1(), "rule__FunctionDefinition__ParamsAssignment_2_1_1");
					put(grammarAccess.getFunctionDefinitionAccess().getReturnAssignment_5(), "rule__FunctionDefinition__ReturnAssignment_5");
					put(grammarAccess.getExpressionAccess().getExpAssignment(), "rule__Expression__ExpAssignment");
					put(grammarAccess.getFirstLevelExpAccess().getArgsAssignment_0(), "rule__FirstLevelExp__ArgsAssignment_0");
					put(grammarAccess.getFirstLevelExpAccess().getOpAssignment_1_0(), "rule__FirstLevelExp__OpAssignment_1_0");
					put(grammarAccess.getFirstLevelExpAccess().getArgsAssignment_1_1(), "rule__FirstLevelExp__ArgsAssignment_1_1");
					put(grammarAccess.getSecondLevelExpAccess().getArgsAssignment_0(), "rule__SecondLevelExp__ArgsAssignment_0");
					put(grammarAccess.getSecondLevelExpAccess().getOpAssignment_1_0(), "rule__SecondLevelExp__OpAssignment_1_0");
					put(grammarAccess.getSecondLevelExpAccess().getArgsAssignment_1_1(), "rule__SecondLevelExp__ArgsAssignment_1_1");
					put(grammarAccess.getThirdLevelExpAccess().getArgsAssignment_0(), "rule__ThirdLevelExp__ArgsAssignment_0");
					put(grammarAccess.getThirdLevelExpAccess().getOpAssignment_1_0(), "rule__ThirdLevelExp__OpAssignment_1_0");
					put(grammarAccess.getThirdLevelExpAccess().getArgsAssignment_1_1(), "rule__ThirdLevelExp__ArgsAssignment_1_1");
					put(grammarAccess.getFourthLevelExpAccess().getArgsAssignment_0(), "rule__FourthLevelExp__ArgsAssignment_0");
					put(grammarAccess.getFourthLevelExpAccess().getOpAssignment_1_0(), "rule__FourthLevelExp__OpAssignment_1_0");
					put(grammarAccess.getFourthLevelExpAccess().getArgsAssignment_1_1(), "rule__FourthLevelExp__ArgsAssignment_1_1");
					put(grammarAccess.getPosIntegerAccess().getValAssignment(), "rule__PosInteger__ValAssignment");
					put(grammarAccess.getNegIntegerAccess().getValAssignment_1(), "rule__NegInteger__ValAssignment_1");
					put(grammarAccess.getMyVariableAccess().getVarAssignment(), "rule__MyVariable__VarAssignment");
					put(grammarAccess.getPosBoolAccess().getValAssignment(), "rule__PosBool__ValAssignment");
					put(grammarAccess.getNegBoolAccess().getValAssignment_1(), "rule__NegBool__ValAssignment_1");
					put(grammarAccess.getMyStringAccess().getValAssignment(), "rule__MyString__ValAssignment");
					put(grammarAccess.getIfControlFlowAccess().getNameAssignment_0(), "rule__IfControlFlow__NameAssignment_0");
					put(grammarAccess.getIfControlFlowAccess().getCondAssignment_2(), "rule__IfControlFlow__CondAssignment_2");
					put(grammarAccess.getIfControlFlowAccess().getIftrueAssignment_4(), "rule__IfControlFlow__IftrueAssignment_4");
					put(grammarAccess.getIfControlFlowAccess().getIffalseAssignment_6(), "rule__IfControlFlow__IffalseAssignment_6");
					put(grammarAccess.getPreDefFunctionCallAccess().getFunctionAssignment_0(), "rule__PreDefFunctionCall__FunctionAssignment_0");
					put(grammarAccess.getPreDefFunctionCallAccess().getArgsAssignment_2_0(), "rule__PreDefFunctionCall__ArgsAssignment_2_0");
					put(grammarAccess.getPreDefFunctionCallAccess().getArgsAssignment_2_1_1(), "rule__PreDefFunctionCall__ArgsAssignment_2_1_1");
					put(grammarAccess.getUserDefFunctionCallAccess().getFunctionAssignment_0(), "rule__UserDefFunctionCall__FunctionAssignment_0");
					put(grammarAccess.getUserDefFunctionCallAccess().getArgsAssignment_2_0(), "rule__UserDefFunctionCall__ArgsAssignment_2_0");
					put(grammarAccess.getUserDefFunctionCallAccess().getArgsAssignment_2_1_1(), "rule__UserDefFunctionCall__ArgsAssignment_2_1_1");
					put(grammarAccess.getListAccess().getElemsAssignment_2_0(), "rule__List__ElemsAssignment_2_0");
					put(grammarAccess.getListAccess().getElemsAssignment_2_1_1(), "rule__List__ElemsAssignment_2_1_1");
					put(grammarAccess.getPreDefFunctionAccess().getNameAssignment(), "rule__PreDefFunction__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser typedParser = (edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser) parser;
			typedParser.entryRuleLista();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ListaCompilerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ListaCompilerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
