/*
 * generated by Xtext
 */
package edu.upb.compilacion.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import edu.upb.compilacion.services.ListaCompilerGrammarAccess;

public class ListaCompilerParser extends AbstractContentAssistParser {
	
	@Inject
	private ListaCompilerGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser createParser() {
		edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser result = new edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getListaAccess().getGroup(), "rule__Lista__Group__0");
					put(grammarAccess.getListaAccess().getNameAssignment_1(), "rule__Lista__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser typedParser = (edu.upb.compilacion.ui.contentassist.antlr.internal.InternalListaCompilerParser) parser;
			typedParser.entryRuleLista();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ListaCompilerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ListaCompilerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
