/**
 * generated by Xtext
 */
package edu.upb.compilacion.ui.contentassist;

import edu.upb.compilacion.ui.contentassist.AbstractListaCompilerProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ListaCompilerProposalProvider extends AbstractListaCompilerProposalProvider {
}
