/*
 * generated by Xtext
 */
package edu.upb.compilacion.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import edu.upb.compilacion.ui.internal.ListaCompilerActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ListaCompilerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ListaCompilerActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ListaCompilerActivator.getInstance().getInjector(ListaCompilerActivator.EDU_UPB_COMPILACION_LISTACOMPILER);
	}
	
}
